import connectDB from '../../../middleware/db'
import User from '../../../models/User'
import Lawyer from '../../../models/Lawyer'

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  // Protect with secret key
  const key = req.headers['x-seed-key']
  if (key !== 'jj_seed_2024') return res.status(403).json({ error: 'Forbidden' })

  try {
    await connectDB()

    // Idempotent: skip if lawyers already exist
    const existingCount = await Lawyer.countDocuments({ isVerified: true })
    if (existingCount >= 15) {
      return res.status(200).json({ message: 'Database already has lawyers', count: existingCount })
    }

    const LAWYERS = [
      {
        name: 'Adv. Rajesh Kumar Sharma',
        city: 'Delhi', state: 'Delhi',
        specializations: ['Criminal Defence', 'Constitutional Law'],
        courts: ['Supreme Court', 'High Court'],
        experience: 22, experienceLevel: 'senior',
        consultationFee: 5000,
        averageRating: 4.9, totalReviews: 187,
        languages: ['English', 'Hindi'],
        bio: 'Senior advocate with 22 years of experience in criminal defence and constitutional matters. Former Additional Advocate General. Has argued landmark cases before the Supreme Court of India.',
        designation: 'Senior Advocate',
        barRegistrationNumber: 'D/1247/2003',
        barCouncilState: 'Delhi',
        yearOfEnrollment: 2003,
        consultationModes: ['In-Person', 'Video Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        availableTimeFrom: '10:00', availableTimeTo: '18:00',
      },
      {
        name: 'Adv. Priya Mehta',
        city: 'Mumbai', state: 'Maharashtra',
        specializations: ['Family Law', 'Divorce'],
        courts: ['High Court', 'Family Court'],
        experience: 12, experienceLevel: 'mid',
        consultationFee: 3000,
        averageRating: 4.8, totalReviews: 142,
        languages: ['English', 'Hindi', 'Marathi'],
        bio: 'Compassionate family law specialist helping clients navigate divorce, child custody, and domestic violence cases. Known for mediation-first approach and sensitive case handling.',
        designation: 'Advocate',
        barRegistrationNumber: 'MH/5623/2013',
        barCouncilState: 'Maharashtra',
        yearOfEnrollment: 2013,
        consultationModes: ['In-Person', 'Video Call', 'Phone Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        availableTimeFrom: '09:00', availableTimeTo: '19:00',
      },
      {
        name: 'Adv. Arjun Venkatesh',
        city: 'Bangalore', state: 'Karnataka',
        specializations: ['Corporate Law', 'Intellectual Property'],
        courts: ['High Court', 'District Court'],
        experience: 15, experienceLevel: 'senior',
        consultationFee: 7500,
        averageRating: 4.9, totalReviews: 98,
        languages: ['English', 'Hindi', 'Kannada'],
        bio: 'Corporate law specialist advising Fortune 500 companies and tech startups on M&A, IP protection, and regulatory compliance. Former in-house counsel at a leading IT firm.',
        designation: 'Senior Advocate',
        barRegistrationNumber: 'KA/3891/2010',
        barCouncilState: 'Karnataka',
        yearOfEnrollment: 2010,
        consultationModes: ['Video Call', 'In-Person'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        availableTimeFrom: '10:00', availableTimeTo: '17:00',
      },
      {
        name: 'Adv. Sunita Rao',
        city: 'Chennai', state: 'Tamil Nadu',
        specializations: ['Property Law', 'Civil Disputes'],
        courts: ['High Court', 'District Court'],
        experience: 18, experienceLevel: 'senior',
        consultationFee: 4000,
        averageRating: 4.7, totalReviews: 156,
        languages: ['English', 'Tamil', 'Hindi'],
        bio: 'Veteran property law advocate with deep expertise in land title disputes, RERA compliance, and civil litigation across Tamil Nadu courts. Has resolved 500+ property disputes.',
        designation: 'Senior Advocate',
        barRegistrationNumber: 'TN/2145/2007',
        barCouncilState: 'Tamil Nadu',
        yearOfEnrollment: 2007,
        consultationModes: ['In-Person', 'Phone Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        availableTimeFrom: '09:30', availableTimeTo: '17:30',
      },
      {
        name: 'Adv. Mohammed Faizal Khan',
        city: 'Hyderabad', state: 'Telangana',
        specializations: ['Labour Law', 'Consumer Rights'],
        courts: ['High Court', 'Consumer Forum', 'Tribunal'],
        experience: 10, experienceLevel: 'mid',
        consultationFee: 2000,
        averageRating: 4.6, totalReviews: 89,
        languages: ['English', 'Hindi', 'Telugu', 'Urdu'],
        bio: 'Dedicated advocate fighting for workers\' rights and consumer protection. Has won landmark cases against major corporations in labour tribunals and consumer forums.',
        designation: 'Advocate',
        barRegistrationNumber: 'TS/4521/2015',
        barCouncilState: 'Telangana',
        yearOfEnrollment: 2015,
        consultationModes: ['In-Person', 'Video Call', 'Phone Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        availableTimeFrom: '08:00', availableTimeTo: '20:00',
      },
      {
        name: 'Adv. Deepa Kulkarni',
        city: 'Pune', state: 'Maharashtra',
        specializations: ['Cyber Law', 'Intellectual Property'],
        courts: ['High Court', 'District Court'],
        experience: 8, experienceLevel: 'mid',
        consultationFee: 3500,
        averageRating: 4.8, totalReviews: 67,
        languages: ['English', 'Hindi', 'Marathi'],
        bio: 'Cyber law expert handling data privacy, online fraud, social media defamation, and IT Act cases. Regularly consulted by tech companies on DPDP Act compliance.',
        designation: 'Advocate',
        barRegistrationNumber: 'MH/7832/2017',
        barCouncilState: 'Maharashtra',
        yearOfEnrollment: 2017,
        consultationModes: ['Video Call', 'Phone Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        availableTimeFrom: '10:00', availableTimeTo: '18:00',
      },
      {
        name: 'Adv. Sanjay Banerjee',
        city: 'Kolkata', state: 'West Bengal',
        specializations: ['Criminal Defence', 'Bail & Custody'],
        courts: ['Supreme Court', 'High Court', 'Sessions Court'],
        experience: 25, experienceLevel: 'senior',
        consultationFee: 6000,
        averageRating: 4.9, totalReviews: 213,
        languages: ['English', 'Hindi', 'Bengali'],
        bio: 'One of Kolkata\'s most respected criminal defence advocates with 25 years at the Bar. Specializes in bail matters, murder trials, and white-collar crime defence.',
        designation: 'Senior Advocate',
        barRegistrationNumber: 'WB/1089/2000',
        barCouncilState: 'West Bengal',
        yearOfEnrollment: 2000,
        consultationModes: ['In-Person'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        availableTimeFrom: '11:00', availableTimeTo: '16:00',
      },
      {
        name: 'Adv. Nisha Patel',
        city: 'Ahmedabad', state: 'Gujarat',
        specializations: ['Taxation', 'Corporate Law'],
        courts: ['High Court', 'Tribunal'],
        experience: 14, experienceLevel: 'senior',
        consultationFee: 4500,
        averageRating: 4.7, totalReviews: 103,
        languages: ['English', 'Hindi', 'Gujarati'],
        bio: 'Tax litigation specialist with deep knowledge of GST, Income Tax appeals, and corporate taxation. Advises SMEs and large businesses on tax planning and compliance.',
        designation: 'Advocate',
        barRegistrationNumber: 'GJ/3456/2011',
        barCouncilState: 'Gujarat',
        yearOfEnrollment: 2011,
        consultationModes: ['In-Person', 'Video Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        availableTimeFrom: '09:00', availableTimeTo: '18:00',
      },
      {
        name: 'Adv. Vikram Singh Rathore',
        city: 'Jaipur', state: 'Rajasthan',
        specializations: ['Civil Disputes', 'Property Law'],
        courts: ['High Court', 'District Court'],
        experience: 20, experienceLevel: 'senior',
        consultationFee: 3000,
        averageRating: 4.6, totalReviews: 178,
        languages: ['English', 'Hindi'],
        bio: 'Renowned civil litigator in Rajasthan with expertise in property disputes, land acquisition matters, and inheritance conflicts. Known for thorough case preparation.',
        designation: 'Senior Advocate',
        barRegistrationNumber: 'RJ/2234/2005',
        barCouncilState: 'Rajasthan',
        yearOfEnrollment: 2005,
        consultationModes: ['In-Person', 'Phone Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        availableTimeFrom: '09:00', availableTimeTo: '17:00',
      },
      {
        name: 'Adv. Aarti Mishra',
        city: 'Lucknow', state: 'Uttar Pradesh',
        specializations: ['Family Law', 'Consumer Rights'],
        courts: ['High Court', 'Family Court', 'Consumer Forum'],
        experience: 9, experienceLevel: 'mid',
        consultationFee: 1500,
        averageRating: 4.5, totalReviews: 74,
        languages: ['English', 'Hindi'],
        bio: 'Empathetic family law practitioner helping clients through divorce, maintenance, and custody matters. Also handles consumer complaints against banks and insurance companies.',
        designation: 'Advocate',
        barRegistrationNumber: 'UP/6712/2016',
        barCouncilState: 'Uttar Pradesh',
        yearOfEnrollment: 2016,
        consultationModes: ['In-Person', 'Video Call', 'Phone Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        availableTimeFrom: '10:00', availableTimeTo: '19:00',
      },
      {
        name: 'Adv. Rohan Deshmukh',
        city: 'Mumbai', state: 'Maharashtra',
        specializations: ['Criminal Defence', 'Cyber Law'],
        courts: ['High Court', 'Sessions Court', 'District Court'],
        experience: 6, experienceLevel: 'mid',
        consultationFee: 2500,
        averageRating: 4.4, totalReviews: 52,
        languages: ['English', 'Hindi', 'Marathi'],
        bio: 'Young and dynamic criminal defence lawyer with a specialization in cybercrime cases. Handles cases related to online fraud, hacking, identity theft, and social media crimes.',
        designation: 'Advocate',
        barRegistrationNumber: 'MH/9045/2019',
        barCouncilState: 'Maharashtra',
        yearOfEnrollment: 2019,
        consultationModes: ['Video Call', 'Phone Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        availableTimeFrom: '08:00', availableTimeTo: '22:00',
      },
      {
        name: 'Adv. Kavitha Iyer',
        city: 'Chennai', state: 'Tamil Nadu',
        specializations: ['Corporate Law', 'Banking & Finance'],
        courts: ['High Court', 'Tribunal'],
        experience: 16, experienceLevel: 'senior',
        consultationFee: 6000,
        averageRating: 4.8, totalReviews: 91,
        languages: ['English', 'Tamil'],
        bio: 'Banking and finance law specialist with 16 years of experience. Advises banks, NBFCs, and fintech companies on regulatory compliance, loan recovery, and SARFAESI matters.',
        designation: 'Senior Advocate',
        barRegistrationNumber: 'TN/1876/2009',
        barCouncilState: 'Tamil Nadu',
        yearOfEnrollment: 2009,
        consultationModes: ['In-Person', 'Video Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        availableTimeFrom: '09:00', availableTimeTo: '17:00',
      },
      {
        name: 'Adv. Amit Choudhary',
        city: 'Delhi', state: 'Delhi',
        specializations: ['Immigration', 'Constitutional Law'],
        courts: ['Supreme Court', 'High Court'],
        experience: 11, experienceLevel: 'mid',
        consultationFee: 4000,
        averageRating: 4.5, totalReviews: 63,
        languages: ['English', 'Hindi', 'Punjabi'],
        bio: 'Immigration law specialist assisting with visa disputes, OCI/PIO matters, deportation defence, and citizenship issues. Also handles PIL and fundamental rights cases.',
        designation: 'Advocate',
        barRegistrationNumber: 'D/5678/2014',
        barCouncilState: 'Delhi',
        yearOfEnrollment: 2014,
        consultationModes: ['Video Call', 'Phone Call', 'In-Person'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        availableTimeFrom: '10:00', availableTimeTo: '18:00',
      },
      {
        name: 'Adv. Sneha Gupta',
        city: 'Bangalore', state: 'Karnataka',
        specializations: ['Labour Law', 'Civil Disputes'],
        courts: ['High Court', 'District Court', 'Tribunal'],
        experience: 5, experienceLevel: 'junior',
        consultationFee: 1000,
        averageRating: 4.3, totalReviews: 38,
        languages: ['English', 'Hindi', 'Kannada'],
        bio: 'Passionate advocate focused on workers\' rights, wrongful termination cases, and civil dispute resolution. Offers affordable consultations to ensure justice is accessible to all.',
        designation: 'Advocate',
        barRegistrationNumber: 'KA/8901/2020',
        barCouncilState: 'Karnataka',
        yearOfEnrollment: 2020,
        consultationModes: ['Video Call', 'Phone Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        availableTimeFrom: '09:00', availableTimeTo: '20:00',
      },
      {
        name: 'Adv. Rahul Saxena',
        city: 'Hyderabad', state: 'Telangana',
        specializations: ['Property Law', 'Taxation'],
        courts: ['High Court', 'District Court', 'Tribunal'],
        experience: 13, experienceLevel: 'senior',
        consultationFee: 3500,
        averageRating: 4.6, totalReviews: 112,
        languages: ['English', 'Hindi', 'Telugu'],
        bio: 'Property law and taxation expert with extensive experience in real estate transactions, RERA disputes, and income tax litigation across Telangana and Andhra Pradesh.',
        designation: 'Advocate',
        barRegistrationNumber: 'TS/3210/2012',
        barCouncilState: 'Telangana',
        yearOfEnrollment: 2012,
        consultationModes: ['In-Person', 'Video Call'],
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        availableTimeFrom: '10:00', availableTimeTo: '18:00',
      },
    ]

    let inserted = 0
    for (const data of LAWYERS) {
      // Check if this lawyer already exists by bar registration
      const exists = await Lawyer.findOne({ barRegistrationNumber: data.barRegistrationNumber })
      if (exists) continue

      // Create User record
      const email = data.name.toLowerCase().replace(/[^a-z]/g, '') + '@jj247.com'
      const existingUser = await User.findOne({ email })
      let user
      if (existingUser) {
        user = existingUser
      } else {
        user = new User({
          name: data.name,
          email,
          password: 'LawyerJJ2024!',
          role: 'lawyer',
          phone: '98' + Math.floor(Math.random() * 100000000).toString().padStart(8, '0'),
          city: data.city,
          state: data.state,
        })
        await user.save()
      }

      // Create Lawyer record
      const lawyer = new Lawyer({
        user: user._id,
        name: data.name,
        email,
        phone: user.phone,
        city: data.city,
        state: data.state,
        specializations: data.specializations,
        experience: data.experience,
        experienceLevel: data.experienceLevel,
        consultationFee: data.consultationFee,
        averageRating: data.averageRating,
        totalReviews: data.totalReviews,
        bio: data.bio,
        languages: data.languages,
        courts: data.courts,
        barRegistrationNumber: data.barRegistrationNumber,
        barCouncilState: data.barCouncilState,
        yearOfEnrollment: data.yearOfEnrollment,
        designation: data.designation,
        consultationModes: data.consultationModes,
        availableDays: data.availableDays,
        availableTimeFrom: data.availableTimeFrom,
        availableTimeTo: data.availableTimeTo,
        isVerified: true,
        isAvailable: true,
      })
      await lawyer.save()
      inserted++
    }

    return res.status(201).json({ message: `Seeded ${inserted} lawyers successfully`, inserted })
  } catch (err) {
    console.error('Seed error:', err)
    return res.status(500).json({ error: err.message })
  }
}
